### ISSUE TITLE
kernel-4.10, error: implicit declaration of function ‘bio_flags’

### ISSUE THREAD

**Issue by marcin-github** [lanconnected/EnhanceIO#13]
If you have a spare time...:)

make[1]: Entering directory '/usr/src/linux-4.10.1-gentoo'                                                                                                                                                     
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_main.o                                                                                                                                                       
In file included from /usr/src/EnhanceIO/Driver/enhanceio/eio_main.c:37:0:
/usr/src/EnhanceIO/Driver/enhanceio/eio_main.c: In function ‘eio_disk_io’:
/usr/src/EnhanceIO/Driver/enhanceio/eio.h:837:41: error: implicit declaration of function ‘bio_flags’ [-Werror=implicit-function-declaration]
 #define GET_BIO_FLAGS(ebio)             bio_flags((ebio)->eb_bc->bc_bio)
                                         ^
/usr/src/EnhanceIO/Driver/enhanceio/eio_main.c:2147:25: note: in expansion of macro ‘GET_BIO_FLAGS’
       GET_BIO_OP(ebio), GET_BIO_FLAGS(ebio),
                         ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:295: /usr/src/EnhanceIO/Driver/enhanceio/eio_main.o] Błąd 1
make[1]: *** [Makefile:1490: _module_/usr/src/EnhanceIO/Driver/enhanceio] Error 2
make[1]: Leaving directory '/usr/src/linux-4.10.1-gentoo'
make: *** [Makefile:28: modules] Error 2

**Comment by lanconnected** [comment]
try branch 4.10 -- https://github.com/lanconnected/EnhanceIO/tree/4.10
I will add support for post 4.10 kernels to the main branch once the Fedora26 is out - they'll probably have kernel 4.11 in F26.

**Comment by dreamnetua** [comment]
Does not work.
Branch EnhanceIO-4.10

make -C /lib/modules/4.10.8-200.fc25.x86_64/build M= modules V=0
make[1]: Entering directory '/usr/src/kernels/4.10.8-200.fc25.x86_64'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  DESCEND  objtool
/usr/src/kernels/4.10.8-200.fc25.x86_64/tools/build/Makefile.build:32: /usr/src/kernels/4.10.8-200.fc25.x86_64/tools/build/Build.include: No such file or directory
make[5]: *** No rule to make target '/usr/src/kernels/4.10.8-200.fc25.x86_64/tools/build/Build.include'.  Stop.
Makefile:42: recipe for target '/usr/src/kernels/4.10.8-200.fc25.x86_64/tools/objtool/fixdep-in.o' failed
make[4]: *** [/usr/src/kernels/4.10.8-200.fc25.x86_64/tools/objtool/fixdep-in.o] Error 2
/usr/src/kernels/4.10.8-200.fc25.x86_64/tools/build/Makefile.include:4: recipe for target 'fixdep' failed
make[3]: *** [fixdep] Error 2
Makefile:61: recipe for target 'objtool' failed
make[2]: *** [objtool] Error 2
Makefile:1617: recipe for target 'tools/objtool' failed
make[1]: *** [tools/objtool] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.10.8-200.fc25.x86_64'
Makefile:28: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by lanconnected** [comment]
Any feedback?

**Comment by lanconnected** [comment]
merged with master.
