### ISSUE TITLE
building on MANJARO linux

### ISSUE THREAD

**Issue by WarShoe** [lanconnected/EnhanceIO#17]
I am a Manjaro Linux user (sorry, not a developer - no patches), kernel 4.11. I tried to compile the master branch:
```
cd EnhanceIO/Driver/enhanceio
make # no errors
sudo make install
make[1]: Entering directory '/usr/lib/modules/4.11.7-1-MANJARO/build'
scripts/Makefile.build:44: arch/x86/entry/syscalls/Makefile: No such file or directory
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/Makefile'.  Stop.
```

and indeed, there is no 'entry' subdir in: /usr/lib/modules/4.11.7-1-MANJARO/build/arch/x86/

I am not sure, maybe I need to install something?!

**Comment by lanconnected** [comment]
I am sorry to disappoint you, but i'm afraid this is beyond the scope of EIO development, most probably, your kernel build configuration is not entirely correct. I know nothing about MANJARO linux, but I'll leave this issue open for a while, maybe somebody else here could help you? Anyway, thanks for reporting and interest in project.

**Comment by lanconnected** [comment]
Should be repaired in f6f9b08

**Comment by WarShoe** [comment]
yes, it does compile now! Thanks! I need to check now does it work for real or not...

**Comment by lanconnected** [comment]
Thanks for testing. If you have another problem, feel free to file a new issue.
