### ISSUE TITLE
Error building with kernel 4.8.8.2 in Arch Linux.

### ISSUE THREAD

**Issue by hradec** [lanconnected/EnhanceIO#21]
I'm seeing this error: 

![image](https://user-images.githubusercontent.com/806743/29252893-96babbd8-8024-11e7-9d98-534af0da0195.png)

It seems REQ_OP_MASK was added in kernel 4.10. 

As I known nothing about kernel coding, could someone recommend a patch for this? It seems to be related to debugging, so as I want to test it to use for production (want to test it against ZFS, instead of L2ARC), I can leave without debugging for now. 

Unfortunately I can't upgrade the kernel at this point, since it's a production server... :(

**Comment by lanconnected** [comment]
Try commit 87fa33e , pls.

**Comment by hradec** [comment]
Works perfectly now! Thanks a lot!! :)

**Comment by lanconnected** [comment]
Thanks for testing.
