### ISSUE TITLE
"signed integer is greater than maximum" when creating cache

### ISSUE THREAD

**Issue by Poisonsting** [lanconnected/EnhanceIO#27]
Creating a cache on any device using my 1TB SSD results in the following. There is no information in dmesg. I have tried applying the patch described here https://github.com/stec-inc/EnhanceIO/issues/77 to no avail.

>root@pve:~/git/EIO/EnhanceIO/Driver/enhanceio#
>eio_cli create -d /dev/sdc -s /dev/sda1 -p lru -m wb -c btrfsCache
>Cache Name       : btrfsCache
>Source Device    : /dev/sdc
>SSD Device       : /dev/sda1
>Policy           : lru
>Mode             : Write Back
>Block Size       : 4096
>Associativity    : 256
>signed integer is greater than maximum
>Cache creation failed (dmesg can provide you more info)

**Comment by lanconnected** [comment]
This problem was addressed a long time ago in commit 8c68f4b . Are you sure you are using eio_cli from this branch?

**Comment by Poisonsting** [comment]
I'm using eio_cli from your master branch, is that correct? Honestly EnhanceIO has been such a maze of abandoned forks and messy code that I have no idea what I should be installing to get it working properly.

**Comment by Poisonsting** [comment]
I just tried deleting eio_cli from /sbin and replacing it with an exact known correct copy, no dice.

**Comment by lanconnected** [comment]
Yes,eio_cli from master branch should be fine. Please make sure, it is the only eio_cli in your system (i.e., delete it from /sbin and try to run it). eio_do_ioctl function in eio_cli (somewhere nere line ~300) should contain "if libc.ioctl(fd, IOC_TYPE, selfaddress) == SUCCESS:", if it is there and you don't have any other eio_cli copies in your system, then there is some new incompatibility. I that case, i'll need much more information about your environment (distributive, python and kernel version at least). Thanks.

**Comment by Poisonsting** [comment]
Looks like I had another copy under /usr/sbin

Thanks for your help.
