### ISSUE TITLE
Cache creation failed: get_device for cache device failed.

### ISSUE THREAD

**Issue by Poisonsting** [lanconnected/EnhanceIO#32]
After finally finding the offending copy of eio_cli that was causing the max int issue, I've run into a new problem. When running this command: 
> eio_cli create -d /dev/sdc -s /dev/sda1 -p lru -m wb -c btrfsCache

I'm presented with the following output:
>Cache Name       : btrfsCache
>Source Device    : /dev/sdc
>SSD Device       : /dev/sda1
>Policy           : lru
>Mode             : Write Back
>Block Size       : 4096
>Associativity    : 256
>Cache creation failed (dmesg can provide you more info)

dmesg provides this line:
>[1245882.920180] enhanceio: Cache creation failed: get_device for cache device failed.

**Comment by lanconnected** [comment]
EIO tries to open cache device exclusively. Please, make sure, that /dev/sda1 exists and is not open by someone else (i.e., it is not configured as PV, not mounted etc.)

**Comment by Poisonsting** [comment]
I've tried completely wiping the partition table on /dev/sda and starting from scratch, same error.

**Comment by lanconnected** [comment]
Nobody else confirmed there is an issue, closing it for now. If someone runs into it again, feel free to reopen, with some more info preferably. Thanks.
