### ISSUE TITLE
Makefile uses the current kernel source which it shouldn't

### ISSUE THREAD

**Issue by HJarausch** [lanconnected/EnhanceIO#35]
The current Makefile uses uname -r to locate the kernel source and kernel module directory.
This is very unfortunate!
When you have just installed a new kernel (something I do about each week),
you're still using the "old" kernel but you want to re-install modules for the new kernel.
All (Gentoo) packages which need the kernel sources access these via the symbolic link /usr/src/linux.
So, it's custom to set this symlink to the new kernel source before re-installing kernel modules.

With the current Makefile you have to boot into the new kernel before you can re-install the 
EnhanceIO-kernel-module. This way I've lost some data. I had installed a cache in write-back mode
but the new kernel couldn't load the EnhanceIO-kernel-module since these were not there, yet.

I've attached a patch to make Makefile refer to /usr/src/linux which may be different from the
current running kernel.
[Makefile.patch.zip](https://github.com/lanconnected/EnhanceIO/files/1474712/Makefile.patch.zip)

**Comment by marcin-github** [comment]
`All (Gentoo) packages which need the kernel sources access these via the symbolic link /usr/src/linux.
So, it's custom to set this symlink to the new kernel source before re-installing kernel modules.`

it can be easy workarounded in ebuild by seting variable "KERNEL_SOURCE_VERSION" before calling Makefile.
Why do you insert zip file? Plain text is easier to read:)

**Comment by lanconnected** [comment]
It's not a bug, as marcin already explained. You can use KERNEL_SOURCE_VERSION or KERNEL_TREE variables. Or compile it like this: $make -C [kernel_source_path] modules M=[eio_module_source_path]
