### ISSUE TITLE
problem compile on kernel 4.15.x

### ISSUE THREAD

**Issue by sasha181** [lanconnected/EnhanceIO#39]
System PROXMOX VE 5.1. 
kernel version 4.15.17-1-pve
Please, help compile EnhanceIO on this system

make -C /lib/modules/4.15.17-1-pve/build M=/root/src/111/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory '/usr/src/linux-headers-4.15.17-1-pve'
make[2]: *** No rule to make target '/root/src/111/EnhanceIO/Driver/enhanceio/eio_conf.o', needed by '/root/src/111/EnhanceIO/Driver/enhanceio/enhanceio.o'.  Stop.
Makefile:1552: recipe for target '_module_/root/src/111/EnhanceIO/Driver/enhanceio' failed
make[1]: *** [_module_/root/src/111/EnhanceIO/Driver/enhanceio] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.17-1-pve'
Makefile:28: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by lanconnected** [comment]
Hi! Are you sure you have kernel-devel package installed? Current EIO should be compilable on kernels 4.15.x

**Comment by lanconnected** [comment]
Glad to help.
