### ISSUE TITLE
new project

### ISSUE THREAD

**Issue by Raboo** [lanconnected/EnhanceIO#4]
Hi,

Since EnhanceIO is considered abandonware and these 3 repositories try to make an effort of evolvning the project:
https://github.com/lanconnected/EnhanceIO
https://github.com/Frontier314/EnhanceIO
https://github.com/d4fseeker/EnhanceIO

I would suggest that you all 3 communicate and fork EnhanceIO into a new project where all 3 repositories are merged into one EnhanceIO-ng. And doing it proper by creating a organization that invites everyone that wants to be a part of the project, thus not having something that relies on one persons interest to continue the development of EnhanceIO.

And then look at all the pull requests that the original project have and try to merge them into EnhanceIO-ng.

That way the community will perhaps notice that there is a new project that is more up to date and still alive.

**Comment by WarShoe** [comment]
Is the project alive?! What is it status?

**Comment by lanconnected** [comment]
Thanks for asking. We will support our fork. For now, it should work on RHEL6 and RHEL7 kernels (2.6.32, 3.10) including openvz ones, if you want to use it on those systems, download branch tagged rc0. Support of modern kernels (>4.3, i.e., those found in fedora) is work-in-progress and could be found in master branch. If anything goes wrong for you, don't hesitate and file the issue - those are very welcome. Patches are welcome, too, but it seems, that there are not many of those willing to contribute.

**Comment by Raboo** [comment]
Sorry guys, I've been drowning in work and personal life stuff. But what happened was that I created the github organization EnhanceIO and invited all major forks owners into the organization. But no one of the major forks moved their code into the new repo.

**Comment by Raboo** [comment]
Closing this issue due to lack of interest/momentum.
If @lanconnected ever wants to use the use the https://github.com/EnhanceIO organization you have a pending invite and it's at your disposal.
