### ISSUE TITLE
Is this fork still maintained?

### ISSUE THREAD

**Issue by adamryczkowski** [lanconnected/EnhanceIO#41]
I get directed to your fork by this Wikipedia article: https://en.wikipedia.org/wiki/EnhanceIO
I wonder if this fork is still maintained? What is the latest kernel it was tested with?

**Comment by ojgarciab** [comment]
This was the last commit (Compatibility for kernels >= 4.14), 9 months ago: https://github.com/lanconnected/EnhanceIO/commit/69565a24e9968612f0878e0645b4ce72bd92ad6e

**Comment by ojgarciab** [comment]
I used it without write-back in root (global) device. I can't help you with installing instructions. I had a trick to compile the new code with old dkms package, but it was almost two years ago. Now I'm using [lvmcache](http://man7.org/linux/man-pages/man7/lvmcache.7.html).

**Comment by adamryczkowski** [comment]
I just tried it on XUbuntu 16.04 virtual guest under VirtualBox for non-root drive. The installation instructions worked flawlessly and there were no problems whatsoever. I tested write back and it really works. Udev scripts also were able to restore the device automatically after reboot. Since both virtual block devices I used for testing were backed by the same SSD drive, I cannot vouch for the actual caching performance, but definitely both "ssd" and "spinning disk" parts were used, when using the eio device.

The kernel was `4.15.0-34-generic`.

**Comment by lanconnected** [comment]
Hi guys! Thanks a lot for your interest in my work, this fork is maintained, and i'll do my best to keep compatibility with modern kernels and to address reported issues. The documentation is a bit (quite a big bit) outdated, sorry for that, i'll get to it once i add all new features i want to the code. If somebody is willing to help with documentation, don't hesitate to contact me :)
We are using enhanceio intensively in our internal projects, always in write-back mode and we did not have any data loss or crashes for the last 2 years or so. That is the main reason there are no new commits - we are (almost) satisfied with the current code. There are packages available for RHEL6 kernels, if someone is interested, i'll add .spec file and packaging instructions.

**Comment by ojgarciab** [comment]
Thanks @lanconnected, I stopped using enhanceio due to the increasing difficulty of compiling using Ubuntu / DKMS (to avoid recompiling every kernel update).
I'll give it a try later and help with documentation related to debian / ubuntu, but I don't know when I'll have time to do it :( I would like to help.

**Comment by adamryczkowski** [comment]
That is a great news. How about the LFU caching algorithm, do you have any plans on implementing it? cf. https://github.com/stec-inc/EnhanceIO/issues/91

**Comment by pasikarkkainen** [comment]
@lanconnected Hey! You mentioned earlier in this issue that you're happily using EnhanceIO on el6. Are you also using it on el7 these days, or still on el6 only? I'm interested in stability experiences on el7 (from others aswell). Thanks!

**Comment by pasikarkkainen** [comment]
Bump. How's the stability on el7 ?

**Comment by onlyjob** [comment]
> Do you know of any packaging of your fork to Debian format (.deb)?

@adamryczkowski, here is the EnhanceIO package from official Debian repositories:

  https://packages.debian.org/search?searchon=sourcenames&keywords=enhanceio

As of 2020 the package is based on this repository.
