### ISSUE TITLE
configuring problem

### ISSUE THREAD

**Issue by pipes80-collab** [lanconnected/EnhanceIO#62]
Configurazione di enhanceio-dkms (0+git20190417.5815670-1)...
Removing old enhanceio-0+git20190417.5815670 DKMS files...

------------------------------
Deleting module version: 0+git20190417.5815670
completely from the DKMS tree.
------------------------------
Done.
Loading new enhanceio-0+git20190417.5815670 DKMS files...
Building for 5.13.0-trunk-amd64
Building initial module for 5.13.0-trunk-amd64
Error! Bad return status for module build on kernel: 5.13.0-trunk-amd64 (x86_64)
Consult /var/lib/dkms/enhanceio/0+git20190417.5815670/build/make.log for more information.
Si sono verificati degli errori nell'elaborazione:.............................] 
 enhanceio-dkms
 enhanceio
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Ristovski** [comment]
EnhanceIO does not build/work on newer kernels. A viable alternative might be https://github.com/akiradeveloper/dm-writeboost

**Comment by pipes80-collab** [comment]
I'll try tomorrow...i don't understand there Is on Debian experimental kernel repository

**Comment by pipes80-collab** [comment]
good that is work...now it's hard to configure

**Comment by onlyjob** [comment]
@pipes80-collab You are not suppose to use Debian "experimental" repository, unless you know what you  are doing.

_dm-writeboost_ is easy enough to use: just check "*writeboost*" and "*dm-writeboost-dkms*" packages.

**Comment by pipes80-collab** [comment]
I have try debian experimental this week end for gaming and watch work more game but i can't install wine
